# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: "localheinz"

branding:
  icon: "box"
  color: "green"

description: "Sets a COMPOSER_ROOT_VERSION environment variable from the value of the branch alias defined in composer.json."

inputs:
  branch:
    description: "Name of the branch, e.g. \"main\""
    required: false
    default: "main"
  path:
    description: "Path in which to look for composer.json"
    required: false
    default: "."

name: "composer-root-version-action"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.branch }}"
    - "${{ inputs.path }}"
